### PR TITLE
Adding SNIServerName support for BIGIPv16.1 or more

### PR DESCRIPTION
**Pull request by nandakishorepeddi**
Added SNIServerName support for BIGIPv16.1 and above versions.

### CODE REVIEW

**Review by subbuv26 — APPROVED** [review]
LGTM

**Review by vklohiya — APPROVED** [review]
LGTM

**Review by agupta49 — APPROVED** [review]
LGTM

**Review by chandrajr — COMMENTED** [review]
minor changes looks good

**Pull request merged**
